---
os: linux
dist: xenial
before_install:
  - "python3 -m pip install --upgrade pip"
install:
  - "pip3 install -r requirements.txt"
  - "python3 setup.py install"
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
script:
  - "python3 tests/data.py"
  - "python3 tests/gui.py"


